print('Введите три числа от 0 до 255 включительно, обозначающие оттенки красного, зелёного и синего. После каждого числа нажмите Enter')
r = hex(int(input('r = ')))[2:4].upper().zfill(2)  # или rjust(2,'0')
g = hex(int(input('g = ')))[2:4].upper().zfill(2)  # или rjust(2,'0')
b = hex(int(input('b = ')))[2:4].upper().zfill(2)  # или rjust(2,'0')
print('Кодировка цвета: #' + r + g + b)
